version: '3'

services:
  app:
    build: .
    labels:
      - "traefik.http.routers.automotron-v2.rule=Host(`automotron-v2.lipsumar.io`)"
      - "traefik.http.routers.automotron-v2.tls.certresolver=le"
      - "traefik.http.routers.automotron-v2.entrypoints=websecure"
      - "traefik.docker.network=traefik-external"
    networks:
      - traefik-external

networks:
  traefik-external:
    external: true
  internal:
    external: false