version: '3'

services:
  app:
    build: .
    labels:
      - 'traefik.http.routers.automotron-v2.rule=Host(`automotron.io`) && Path(`/editor`)'
      - 'traefik.http.routers.automotron-v2.tls.certresolver=le'
      - 'traefik.http.routers.automotron-v2.entrypoints=websecure'
      - 'traefik.docker.network=traefik-external'
    volumes:
      - ./previews:/usr/src/app/previews
    environment:
      - MONGO_URL=mongodb://mongo:27017/prod
    networks:
      - traefik-external
      - internal
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - internal
    labels:
      - 'traefik.enable=false'

networks:
  traefik-external:
    external: true
  internal:
    external: false
